##############################################################################
#  Copyright Christopher Kormanyos 2023.
#  Distributed under The Unlicense.

name: avr-gcc-build
on:
  push:
    branches:
      - '**'
  pull_request:
jobs:
  avr-gcc-build-native:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: update-tools
        run: sudo apt install libgmp-dev libmpfr-dev libmpc-dev
      - name: avr-gcc-build-001-make-dirs
        run: |
          echo "run avr-gcc-001-make-dirs.sh"
          ./avr-gcc-001-make-dirs.sh
      - name: avr-gcc-build-002-build-isl.sh
        run: |
          echo "run avr-gcc-002-build-isl.sh"
          ./avr-gcc-002-build-isl.sh
          echo "verify build isl"
          ls -la /home/runner/work/avr-gcc-build/avr-gcc-build/local/isl-0.15
