##############################################################################
#  Copyright Christopher Kormanyos 2023.
#  Distributed under The Unlicense.

name: avr-gcc-build
on:
  push:
    branches:
      - '**'
  pull_request:
jobs:
  avr-gcc-build-native:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: update-prerequisites
        run: sudo apt install libgmp-dev libmpfr-dev libmpc-dev
      - name: update-buiild-essentials
        run: sudo apt install mingw-w64 gcc g++ bzip2 xz-utils git autoconf texinfo bison flex yacc
      - name: avr-gcc-build-001-make-dirs
        run: |
          echo "run avr-gcc-001-make-dirs.sh"
          ./avr-gcc-001-make-dirs.sh
      - name: avr-gcc-build-002-build-gmp
        run: |
          echo "run avr-gcc-002-build-gmp.sh"
          ./avr-gcc-002-build-gmp.sh
          echo "verify build gmp"
          ls -la /home/runner/work/avr-gcc-build/avr-gcc-build/local/gmp-6.3.0
      - name: avr-gcc-build-003-build-mpfr
        run: |
          echo "run avr-gcc-003-build-mpfr.sh"
          ./avr-gcc-003-build-mpfr.sh
          echo "verify build mpfr"
          ls -la /home/runner/work/avr-gcc-build/avr-gcc-build/local/mpfr-4.2.1
      - name: avr-gcc-build-004-build-mpc
        run: |
          echo "run avr-gcc-004-build-mpc.sh"
          ./avr-gcc-004-build-mpc.sh
          echo "verify build mpc"
          ls -la /home/runner/work/avr-gcc-build/avr-gcc-build/local/mpc-1.2.1
      - name: avr-gcc-build-005-build-isl
        run: |
          echo "run avr-gcc-005-build-isl.sh"
          ./avr-gcc-005-build-isl.sh
          echo "verify build isl"
          ls -la /home/runner/work/avr-gcc-build/avr-gcc-build/local/isl-0.15
      - name: avr-gcc-build-010-build-binutils
        run: |
          echo "run avr-gcc-010-build-binutils.sh"
          ./avr-gcc-010-build-binutils.sh
          echo "verify build binutils"
          ls -la /home/runner/work/avr-gcc-build/avr-gcc-build/local/gcc-13.2.0-avr/bin
      - name: avr-gcc-build-020-build-gcc
        run: |
          source ./tmprcfile
          echo "run avr-gcc-020-build-gcc.sh"
          ./avr-gcc-020-build-gcc.sh
          echo "verify build gcc"
          ls -la /home/runner/work/avr-gcc-build/avr-gcc-build/local/gcc-13.2.0-avr/bin
