##############################################################################
#  Copyright Christopher Kormanyos 2023.
#  Distributed under The Unlicense.

name: avr-gcc-build
on:
  push:
    branches:
      - '**'
  pull_request:
  schedule:
    - cron: '30 10 1 * *' # run at 10:30 AM every first day of the month (UTC, see also https://cloud.google.com/scheduler/docs/configuring/cron-job-schedules?hl=en)
jobs:
  avr-gcc-build-native:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        hostname: [ x86_64-linux-gnu ]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: update-buiild-essentials
        run: sudo apt install mingw-w64 xz-utils autoconf texinfo
      - name: avr-gcc-010-make-prereq_binutils
        run: |
          echo "run avr-gcc-010-make-prereq_binutils.sh"
          ./avr-gcc-010-make-prereq_binutils.sh ${{ matrix.hostname }}
          echo "verify build binutils"
          ls -la ${{ runner.workspace }}/avr-gcc-build/local/gcc-13.2.0-avr/bin
          ls -la ${{ runner.workspace }}/avr-gcc-build/local/gcc-13.2.0-avr/bin/avr-ld
      - name: avr-gcc-020-make-gcc
        run: |
          echo "run avr-gcc-020-make-gcc.sh"
          ./avr-gcc-020-make-gcc.sh ${{ matrix.hostname }}
          echo "verify build gcc"
          ls -la ${{ runner.workspace }}/avr-gcc-build/local/gcc-13.2.0-avr/bin
          ls -la ${{ runner.workspace }}/avr-gcc-build/local/gcc-13.2.0-avr/bin/avr-gcc
      - name: avr-gcc-030-make-avr-libc
        run: |
          echo "run avr-gcc-030-make-avr-libc.sh"
          ./avr-gcc-030-make-avr-libc.sh ${{ matrix.hostname }}
