##############################################################################
#  Copyright Christopher Kormanyos 2023.
#  Distributed under The Unlicense.

name: avr-gcc-build
on:
  push:
    branches:
      - '**'
  pull_request:
  schedule:
    - cron: '30 10 1 * *' # run at 10:30 AM every first day of the month (UTC, see also https://cloud.google.com/scheduler/docs/configuring/cron-job-schedules?hl=en)
jobs:
  avr-gcc-build-native:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        hostname: [ x86_64-unknown-linux-gnu ]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: update-buiild-essentials
        run: sudo apt install mingw-w64 xz-utils autoconf texinfo
      - name: avr-gcc-build-001-make-install
        run: |
          echo "run avr-gcc-001-make-install.sh"
          ./avr-gcc-001-make-install.sh ${{ matrix.hostname }}
          echo "verify build binutils"
      - name: avr-gcc-build-verify-artifacts
        run: |
          ls -la ${{ runner.workspace }}/avr-gcc-build/local/gcc-13.2.0-avr/bin
          ls -la ${{ runner.workspace }}/avr-gcc-build/local/gcc-13.2.0-avr/bin/avr-ld.exe

#      - name: avr-gcc-build-clone-avr-libc
#        run: |
#          echo "Clone stevenj/avr-libc3"
#          git clone -b master --depth 1 https://github.com/stevenj/avr-libc3 ${{ runner.workspace }}/avr-gcc-build/gcc_build/avr-libc3
#          cd ${{ runner.workspace }}/avr-gcc-build/gcc_build/avr-libc3
#          git checkout d09c2a61764aced3274b6dde4399e11b0aee4a87
#      - name: avr-gcc-build-avr-libc
#        shell: bash -l {0}
#        run: |
#          echo "run avr-gcc-030-build-avr-libc.sh"
#          ./avr-gcc-030-build-avr-libc.sh
